version: '3'

services:
  gateway:
    container_name: gateway_container
    build:
      context: .
    ports:
      - 4242:4242
    env_file:
      - .env
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true
